# Ubuntu Bionic doesn't include Python 2 by default so we have to ensure it is
# installed. Based on: https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: ensure python2 is installed
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: check_python
    changed_when: check_python.stdout != ''

  - name: ensure aptitude is installed
    raw: test -e /usr/bin/aptitude || (apt -y update && apt install -y aptitude)
    register: check_aptitude

  # Updates and upgrades packages

  - name: ensure apt lists cache is clear
    file:
      path: '/var/lib/apt/lists'
      state: absent

  - name: ensure needed apt lists cache directories exists
    file:
      path: '{{ item }}'
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - '/var/lib/apt/lists'
      - '/var/lib/apt/lists/partials'

  - name: ensure apt is updated
    apt:
      update_cache: yes

  - name: ensure apt is upgraded
    apt:
      upgrade: yes

  # Fix locale settings to en_US.UTF-8
  - name: ensure /etc/environment has been overrided for LANGUAGE
    lineinfile:
      dest: /etc/environment
      line: "LANGUAGE=en_US.UTF-8"

  - name: ensure /etc/environment has been overrided for LANG
    lineinfile:
      dest: /etc/environment
      line: "LANG=en_US.UTF-8"

  - name: ensure /etc/environment has been overrided for LC_ALL
    lineinfile:
      dest: /etc/environment
      line: "LC_ALL=en_US.UTF-8"
